name: Publicar no GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurar uv e Python
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Instalar dependências Python
        run: uv sync --no-install-workspace

      - name: Configurar Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Renderizar Livro Quarto
        run: uv run quarto render

      - name: Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book